### ISSUE TITLE
more info on karate.edgelist?

### ISSUE THREAD

**Issue by worthless443** [bagrow/datatools#3]
Could anyone list more info on `karate.edgelist`?

**Comment by djberenberg** [comment]
@PatxiofromAlphensign  at first glance it looks like this: https://en.wikipedia.org/wiki/Zachary%27s_karate_club

**Comment by bagrow** [comment]
Yeah, that's what it is. Here's a page about the data: http://konect.cc/networks/ucidata-zachary/
